### ISSUE TITLE
Support general updating dependencies?

### ISSUE THREAD

**Issue by okainov** [pre-commit/sync-pre-commit-deps#13]
It would be great if the hook could update all dependencies and not just sync them. For example, in our projects it's incredibly common to have something like this:
```yaml
  -   repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
        -   id: flake8
            additional_dependencies: [
              darglint==1.8.1,
              flake8-2020==1.8.1,
              flake8-alfred==1.1.1,
              flake8-builtins==2.1.0,
              flake8-logging-format==0.9.0,
              flake8-mutable==1.2.0,
              flake8-use-fstring==1.4,
              flake8-expression-complexity==0.0.11,
              flake8-variables-names==0.0.6,
              flake8-pyi==23.6.0,
            ]

```

And while the main hook gets updated from time to time, all additional dependencies quickly get forgotten and become out-of date...

**Comment by mxr** [comment]
This is unsupported for the reasons described in https://github.com/pre-commit/pre-commit/issues/1351#issuecomment-594111058

**Comment by WilliamDEdwards** [comment]
This. (Is what I wanted to reply to https://github.com/pre-commit/pre-commit/issues/945#issuecomment-1961857591, but couldn't as 'limited conversation to collaborators'.)
