### ISSUE TITLE
create tags/releases

### ISSUE THREAD

**Issue by Finkregh** [pre-commit/sync-pre-commit-deps#40]
To get the new version of this repo via `pre-commit autoupdate` it would be nice if tags could be created.

Thanks or your work!

**Comment by asottile** [comment]
there are tags, there's only ever been one release so far

**Comment by Finkregh** [comment]
Yeah, sorry. I was just going over the changes in the `.py` file and there have been no functional ones. 🙈 

Thanks again!

**Comment by mxr** [comment]
I suppose there could be a tag for the functionality added in https://github.com/pre-commit/sync-pre-commit-deps/commit/d03e6b446a1aa15050ca115eea16831c2d5106f8
